use_frameworks!

platform :ios, '8.0'

target 'FSTrack_Example' do
  pod 'FSTrack', :path => '../'

  target 'FSTrack_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'Expecta+Snapshots'
  end
end
